# Generated by Django 5.2.7 on 2025-11-06 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_activated',
        ),
    ]
