@WebApplication1_HostAddress = http://localhost:5009

POST {{WebApplication1_HostAddress}}/api/payments/create
Content-Type: application/json
Accept: application/json

{
  "itemName": "Sample Service",
  "amount": 1500.00,
  "firstName": "Jane",
  "lastName": "Doe",
  "email": "jane.doe@example.com",
  "phone": "0771234567",
  "address": "123 Beacon St",
  "city": "Colombo",
  "country": "Sri Lanka"
}

###
