# Generated by Django 5.2.7 on 2025-11-05 11:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Technician', 'Technician'), ('Driver', 'Driver')], max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('invite_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_activated', models.BooleanField(default=False)),
            ],
        ),
    ]
