# Generated by Django 5.2.7 on 2025-11-05 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('manager', models.ForeignKey(blank=True, limit_choices_to={'role': 'Manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branches', to='admin_service.employee')),
            ],
        ),
    ]
